/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function analyse(a: number, b: number, c: number): number;
export function getMedianSmoothed(): number;
export function getDebug(): number;
export function getThresholded(): number;
export function getBodyShape(): number;
export function getFaceShape(): number;
export function getRadialSmoothed(): number;
export function getEdges(): number;
export function __wbg_heatstats_free(a: number): void;
export function __wbg_get_heatstats_min(a: number): number;
export function __wbg_set_heatstats_min(a: number, b: number): void;
export function __wbg_get_heatstats_max(a: number): number;
export function __wbg_set_heatstats_max(a: number, b: number): void;
export function __wbg_get_heatstats_threshold(a: number): number;
export function __wbg_set_heatstats_threshold(a: number, b: number): void;
export function __wbg_quad_free(a: number): void;
export function __wbg_get_quad_topRight(a: number): number;
export function __wbg_set_quad_topRight(a: number, b: number): void;
export function __wbg_get_quad_bottomLeft(a: number): number;
export function __wbg_set_quad_bottomLeft(a: number, b: number): void;
export function __wbg_get_quad_bottomRight(a: number): number;
export function __wbg_set_quad_bottomRight(a: number, b: number): void;
export function __wbg_faceinfo_free(a: number): void;
export function __wbg_get_faceinfo_isValid(a: number): number;
export function __wbg_set_faceinfo_isValid(a: number, b: number): void;
export function __wbg_get_faceinfo_halfwayRatio(a: number): number;
export function __wbg_set_faceinfo_halfwayRatio(a: number, b: number): void;
export function __wbg_get_faceinfo_headLock(a: number): number;
export function __wbg_set_faceinfo_headLock(a: number, b: number): void;
export function __wbg_get_faceinfo_head(a: number): number;
export function __wbg_set_faceinfo_head(a: number, b: number): void;
export function __wbg_get_faceinfo_samplePoint(a: number): number;
export function __wbg_set_faceinfo_samplePoint(a: number, b: number): void;
export function __wbg_get_faceinfo_sampleValue(a: number): number;
export function __wbg_set_faceinfo_sampleValue(a: number, b: number): void;
export function __wbg_get_faceinfo_sampleTemp(a: number): number;
export function __wbg_set_faceinfo_sampleTemp(a: number, b: number): void;
export function __wbg_get_faceinfo_idealSamplePoint(a: number): number;
export function __wbg_set_faceinfo_idealSamplePoint(a: number, b: number): void;
export function __wbg_get_faceinfo_idealSampleValue(a: number): number;
export function __wbg_set_faceinfo_idealSampleValue(a: number, b: number): void;
export function __wbg_get_faceinfo_idealSampleTemp(a: number): number;
export function __wbg_set_faceinfo_idealSampleTemp(a: number, b: number): void;
export function __wbg_get_faceinfo_reason(a: number): number;
export function __wbg_set_faceinfo_reason(a: number, b: number): void;
export function __wbg_get_point_x(a: number): number;
export function __wbg_set_point_x(a: number, b: number): void;
export function __wbg_get_point_y(a: number): number;
export function __wbg_set_point_y(a: number, b: number): void;
export function __wbg_thermalreference_free(a: number): void;
export function __wbg_get_thermalreference_geom(a: number): number;
export function __wbg_set_thermalreference_geom(a: number, b: number): void;
export function __wbg_get_thermalreference_val(a: number): number;
export function __wbg_set_thermalreference_val(a: number, b: number): void;
export function __wbg_get_thermalreference_temp(a: number): number;
export function __wbg_set_thermalreference_temp(a: number, b: number): void;
export function __wbg_analysisresult_free(a: number): void;
export function __wbg_get_analysisresult_motionSum(a: number): number;
export function __wbg_set_analysisresult_motionSum(a: number, b: number): void;
export function __wbg_get_analysisresult_motionThresholdSum(a: number): number;
export function __wbg_set_analysisresult_motionThresholdSum(a: number, b: number): void;
export function __wbg_get_analysisresult_thresholdSum(a: number): number;
export function __wbg_set_analysisresult_thresholdSum(a: number, b: number): void;
export function __wbg_get_analysisresult_frameBottomSum(a: number): number;
export function __wbg_set_analysisresult_frameBottomSum(a: number, b: number): void;
export function __wbg_get_analysisresult_hasBody(a: number): number;
export function __wbg_set_analysisresult_hasBody(a: number, b: number): void;
export function __wbg_get_analysisresult_heatStats(a: number): number;
export function __wbg_set_analysisresult_heatStats(a: number, b: number): void;
export function __wbg_get_analysisresult_face(a: number): number;
export function __wbg_set_analysisresult_face(a: number, b: number): void;
export function __wbg_get_analysisresult_nextState(a: number): number;
export function __wbg_set_analysisresult_nextState(a: number, b: number): void;
export function __wbg_get_analysisresult_thermalReference(a: number): number;
export function __wbg_set_analysisresult_thermalReference(a: number, b: number): void;
export function __wbg_circle_free(a: number): void;
export function __wbg_get_circle_center(a: number): number;
export function __wbg_set_circle_center(a: number, b: number): void;
export function __wbg_get_circle_radius(a: number): number;
export function __wbg_set_circle_radius(a: number, b: number): void;
export function __wbg_get_quad_topLeft(a: number): number;
export function __wbg_set_quad_topLeft(a: number, b: number): void;
export function __wbg_point_free(a: number): void;
export function initialize(a: number, b: number): void;
export function __wbindgen_free(a: number, b: number): void;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number): number;
