project_name: feverscreen
dist: dist

release:
  github:
    owner: feverscreen
    name: feverscreen
  name_template: '{{.Tag}}'

builds:
- id: feverscreen
  binary: feverscreen
  main: ./cmd/feverscreen
  goos:
    - linux
  goarch:
    - arm
  goarm:
    - "7"
  hooks:
    pre:
      - packr
    post:
      - packr clean
  ldflags: -s -w -X main.version={{.Version}}
- id: leptond
  binary: leptond
  main: ./cmd/leptond
  goos:
    - linux
  goarch:
    - arm
  goarm:
    - "7"
  ldflags: -s -w -X main.version={{.Version}}
- id: feverscreen-updater
  binary: feverscreen-updater
  main: ./cmd/feverscreen-updater
  goos:
    - linux
  goarch:
    - arm
  goarm:
    - "7"
  ldflags: -s -w -X main.version={{.Version}}

nfpms:
-
  vendor: The Cacophony Project
  homepage: http://cacophony.org.nz/
  maintainer: Core Developers <coredev@cacophony.org.nz>
  description: Fever detection using thermal cameras
  license: GPL v3.0
  file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}"
  formats:
    - deb
  bindir: /usr/bin
  contents:
    - src: _release/feverscreen.service 
      dst: /etc/systemd/system/feverscreen.service
    - src: _release/feverscreen-updater.service 
      dst: /etc/systemd/system/feverscreen-updater.service
    - src: _release/leptond.service 
      dst: /etc/systemd/system/leptond.service
    - src: webserver/_release/managementd-avahi.service
      dst: /etc/avahi/services/managementd.service
    - src: _release/org.cacophony.leptond.conf 
      dst: /etc/dbus-1/system.d/org.cacophony.leptond.conf
    - src: _release/org.cacophony.feverscreen-updater.conf
      dst: /etc/dbus-1/system.d/org.cacophony.feverscreen-updater.conf
    - src: _release/tko-release-channel 
      dst: /usr/local/bin/tko-release-channel
    - src: _release/tko-update 
      dst: /usr/local/bin/tko-update
    - src: _release/feverscreen-apt-preferences 
      dst: /etc/apt/preferences.d/feverscreen
    - src: _release/feverscreen-only-apt-config 
      dst: /etc/tko/feverscreen-only-apt-config
  scripts:
    postinstall: "_release/postinstall.sh"

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
