language: go
go:
- 1.13.x
script:
- go mod tidy
- git diff --exit-code --quiet || (echo "Please run 'go mod tidy' to clean up the 'go.mod' and 'go.sum' files."; false)
- go vet ./...
- go test ./...

deploy:
  provider: script
  skip_cleanup: true
  script: make release
  on:
    tags: true
    go: "1.13.x"