/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_heatstats_free(a: number): void;
export function __wbg_get_heatstats_min(a: number): number;
export function __wbg_set_heatstats_min(a: number, b: number): void;
export function __wbg_get_heatstats_max(a: number): number;
export function __wbg_set_heatstats_max(a: number, b: number): void;
export function initialize(a: number, b: number): void;
export function extract(a: number, b: number, c: number, d: number, e: number, f: number, g: number): number;
export function smooth(a: number, b: number, c: number): void;
export function __wbg_get_quad_top_left(a: number): number;
export function __wbg_set_quad_top_left(a: number, b: number): void;
export function __wbg_get_quad_top_right(a: number): number;
export function __wbg_set_quad_top_right(a: number, b: number): void;
export function __wbg_get_quad_bottom_left(a: number): number;
export function __wbg_set_quad_bottom_left(a: number, b: number): void;
export function __wbg_get_quad_bottom_right(a: number): number;
export function __wbg_set_quad_bottom_right(a: number, b: number): void;
export function __wbg_faceinfo_free(a: number): void;
export function __wbg_get_faceinfo_is_valid(a: number): number;
export function __wbg_set_faceinfo_is_valid(a: number, b: number): void;
export function __wbg_get_faceinfo_halfway_ratio(a: number): number;
export function __wbg_set_faceinfo_halfway_ratio(a: number, b: number): void;
export function __wbg_get_faceinfo_head_lock(a: number): number;
export function __wbg_set_faceinfo_head_lock(a: number, b: number): void;
export function __wbg_get_faceinfo_head(a: number): number;
export function __wbg_set_faceinfo_head(a: number, b: number): void;
export function __wbg_get_faceinfo_sample_point(a: number): number;
export function __wbg_set_faceinfo_sample_point(a: number, b: number): void;
export function __wbg_get_faceinfo_sample_value(a: number): number;
export function __wbg_set_faceinfo_sample_value(a: number, b: number): void;
export function __wbg_get_point_x(a: number): number;
export function __wbg_set_point_x(a: number, b: number): void;
export function __wbg_get_point_y(a: number): number;
export function __wbg_set_point_y(a: number, b: number): void;
export function __wbg_get_motionstats_motion_sum(a: number): number;
export function __wbg_set_motionstats_motion_sum(a: number, b: number): void;
export function __wbg_get_motionstats_motion_threshold_sum(a: number): number;
export function __wbg_set_motionstats_motion_threshold_sum(a: number, b: number): void;
export function __wbg_get_motionstats_threshold_sum(a: number): number;
export function __wbg_set_motionstats_threshold_sum(a: number, b: number): void;
export function __wbg_get_motionstats_frame_bottom_sum(a: number): number;
export function __wbg_set_motionstats_frame_bottom_sum(a: number, b: number): void;
export function __wbg_get_motionstats_heat_stats(a: number): number;
export function __wbg_set_motionstats_heat_stats(a: number, b: number): void;
export function __wbg_get_motionstats_face(a: number): number;
export function __wbg_set_motionstats_face(a: number, b: number): void;
export function getMedianSmoothed(): number;
export function getThresholded(): number;
export function getHeadHull(): number;
export function getBodyHull(): number;
export function getHeatStats(): number;
export function getHistogram(): number;
export function getRadialSmoothed(): number;
export function getEdges(): number;
export function __wbg_quad_free(a: number): void;
export function __wbg_point_free(a: number): void;
export function __wbg_motionstats_free(a: number): void;
export function __wbg_get_heatstats_threshold(a: number): number;
export function __wbg_set_heatstats_threshold(a: number, b: number): void;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number): number;
export function __wbindgen_free(a: number, b: number): void;
export function __wbindgen_exn_store(a: number): void;
