/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function initialize(a: number, b: number): void;
export function analyse(a: number, b: number): number;
export function getMedianSmoothed(): number;
export function getThresholded(): number;
export function getBodyShape(): number;
export function getHeatStats(): number;
export function getHistogram(): number;
export function getRadialSmoothed(): number;
export function getEdges(): number;
export function __wbg_heatstats_free(a: number): void;
export function __wbg_get_heatstats_min(a: number): number;
export function __wbg_set_heatstats_min(a: number, b: number): void;
export function __wbg_get_heatstats_max(a: number): number;
export function __wbg_set_heatstats_max(a: number, b: number): void;
export function __wbg_quad_free(a: number): void;
export function __wbg_get_quad_top_right(a: number): number;
export function __wbg_set_quad_top_right(a: number, b: number): void;
export function __wbg_get_quad_bottom_left(a: number): number;
export function __wbg_set_quad_bottom_left(a: number, b: number): void;
export function __wbg_get_quad_bottom_right(a: number): number;
export function __wbg_set_quad_bottom_right(a: number, b: number): void;
export function __wbg_faceinfo_free(a: number): void;
export function __wbg_get_faceinfo_is_valid(a: number): number;
export function __wbg_set_faceinfo_is_valid(a: number, b: number): void;
export function __wbg_get_faceinfo_halfway_ratio(a: number): number;
export function __wbg_set_faceinfo_halfway_ratio(a: number, b: number): void;
export function __wbg_get_faceinfo_head_lock(a: number): number;
export function __wbg_set_faceinfo_head_lock(a: number, b: number): void;
export function __wbg_get_faceinfo_head(a: number): number;
export function __wbg_set_faceinfo_head(a: number, b: number): void;
export function __wbg_get_faceinfo_sample_point(a: number): number;
export function __wbg_set_faceinfo_sample_point(a: number, b: number): void;
export function __wbg_get_faceinfo_sample_value(a: number): number;
export function __wbg_set_faceinfo_sample_value(a: number, b: number): void;
export function __wbg_get_faceinfo_sample_temp(a: number): number;
export function __wbg_set_faceinfo_sample_temp(a: number, b: number): void;
export function __wbg_get_point_x(a: number): number;
export function __wbg_set_point_x(a: number, b: number): void;
export function __wbg_get_point_y(a: number): number;
export function __wbg_set_point_y(a: number, b: number): void;
export function __wbg_thermalreference_free(a: number): void;
export function __wbg_get_thermalreference_geom(a: number): number;
export function __wbg_set_thermalreference_geom(a: number, b: number): void;
export function __wbg_get_thermalreference_val(a: number): number;
export function __wbg_set_thermalreference_val(a: number, b: number): void;
export function __wbg_get_thermalreference_temp(a: number): number;
export function __wbg_set_thermalreference_temp(a: number, b: number): void;
export function __wbg_analysisresult_free(a: number): void;
export function __wbg_get_analysisresult_motion_sum(a: number): number;
export function __wbg_set_analysisresult_motion_sum(a: number, b: number): void;
export function __wbg_get_analysisresult_motion_threshold_sum(a: number): number;
export function __wbg_set_analysisresult_motion_threshold_sum(a: number, b: number): void;
export function __wbg_get_analysisresult_threshold_sum(a: number): number;
export function __wbg_set_analysisresult_threshold_sum(a: number, b: number): void;
export function __wbg_get_analysisresult_frame_bottom_sum(a: number): number;
export function __wbg_set_analysisresult_frame_bottom_sum(a: number, b: number): void;
export function __wbg_get_analysisresult_has_body(a: number): number;
export function __wbg_set_analysisresult_has_body(a: number, b: number): void;
export function __wbg_get_analysisresult_heat_stats(a: number): number;
export function __wbg_set_analysisresult_heat_stats(a: number, b: number): void;
export function __wbg_get_analysisresult_face(a: number): number;
export function __wbg_set_analysisresult_face(a: number, b: number): void;
export function __wbg_get_analysisresult_next_state(a: number): number;
export function __wbg_set_analysisresult_next_state(a: number, b: number): void;
export function __wbg_get_analysisresult_thermal_ref(a: number): number;
export function __wbg_set_analysisresult_thermal_ref(a: number, b: number): void;
export function __wbg_circle_free(a: number): void;
export function __wbg_get_circle_center(a: number): number;
export function __wbg_set_circle_center(a: number, b: number): void;
export function __wbg_get_circle_radius(a: number): number;
export function __wbg_set_circle_radius(a: number, b: number): void;
export function __wbg_point_free(a: number): void;
export function __wbg_get_heatstats_threshold(a: number): number;
export function __wbg_get_quad_top_left(a: number): number;
export function __wbg_set_quad_top_left(a: number, b: number): void;
export function __wbg_set_heatstats_threshold(a: number, b: number): void;
export function __wbindgen_free(a: number, b: number): void;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number): number;
